title: Rohan Bafna
description: Rohan Bafna's personal website
email: rohannb@umich.edu
github_url: https://github.com/rohanbafna

plugins:
- jekyll-seo-tag
- jekyll-cache-bust

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "*.nix"
  - "*.lock"
  - "Gemfile"
  - CNAME
